version: "3.8"

services:
  flask_app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    volumes:
      - /tmp:/app/uploads
    # volumes:
    #   # Workaround for ignored shm_size in swarm:
    #   - type: tmpfs
    #     target: /flask_app/uploads
    #     tmpfs:
    #       size: 536870912 # 512M max ; defaults to 64M ; relative to total work_mem?

  celery_worker:
    build:
      context: .
    entrypoint: celery
    command: -A app.celery_app worker -l INFO
    depends_on:
      - flask_app
    volumes:
      - /tmp:/app/uploads

  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
