version: "3.8"

services:
  flask_app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq

  celery_worker:
    build:
      context: .
    entrypoint: celery
    command: -A app.celery_app worker -l INFO
    depends_on:
      - flask_app

  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
